# Generated by Django 5.1 on 2024-08-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RepresentanteFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='housing.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('vivienda', models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0)),
                ('cocina', models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0)),
                ('bano', models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0)),
                ('urgencia_vivienda', models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20)),
                ('urgencia_cocina', models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20)),
                ('urgencia_bano', models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='housing.representantefamilia')),
            ],
        ),
    ]
