# Generated by Django 5.1 on 2024-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_alter_comunidad_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresovivienda',
            name='bano',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='cocina',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_bano',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_cocina',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_vivienda',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='vivienda',
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='agua_potable',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Agua potable'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='ahorro',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Plan de ahorro'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='arboles_frutales',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Arboles frutales'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='banio_diario',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Baño diario'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='capacitaciones',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Capacitaciones comunitarias'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='cerco_vivo',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Cerco vivo'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='chequeo_embarazo',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Chequeos pre y post natales'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='comida_protegida',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Comida protegida'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='divisiones',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Divisiones de suelo'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='emergencia_embarazo',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Plan de emergencia embarazo'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='escuela',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Asistencia a escuela'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='estufa_mejorada',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Estufa mejorada'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='lavar_manos',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Lavarse las manos'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='letrina',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Letrina'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='limpieza',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Limpieza de casa'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='muebles',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Ropa ordenada en muebles'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='peso',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Monitoreo de peso y salud'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='piscicultura',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Piscicultura'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='piso',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='plagas',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Sistema de trojas'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='reciclaje',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Botes de basura'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='sumidero',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Sumidero'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='tuberculos',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Tubérculos'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_agua',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia de agua potable'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_ahorro',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia de ahorro'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_arboles',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia arboles frutales'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_banio',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Baño diario'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_capacitaciones',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia capacitaciones'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_cerco',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia cerco vivo'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_chequeo_embarazo',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia de chequeos'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_comida',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia de comida protegida'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_divisiones',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia de divisiones'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_emergencia_embarazo',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia de plan'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_escuela',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia asistencia a escuela'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_estufa',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia de estufa'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_lavar_manos',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia lavarse las manos'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_letrina',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia letrina'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_limpieza',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia de limpieza'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_muebles',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia ropa ordenada'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_peso',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia de monitoreo'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_piscicultura',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia piscicultura'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_piso',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia de piso'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_plagas',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia sistema de trojas'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_reciclaje',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia botes de basura'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_sumidero',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia sumidero'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_tuberculos',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia tubérculos'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='urgencia_vacunacion',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Realizado con Éxito')], default='en_proceso', max_length=20, verbose_name='Urgencia de vacunación'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='vacunacion',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Plan de vacunación'),
        ),
        migrations.AlterField(
            model_name='progresovivienda',
            name='fecha_registro',
            field=models.DateField(verbose_name='Fecha de Registro'),
        ),
    ]
