# Generated by Django 5.1 on 2024-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_remove_progresovivienda_bano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresovivienda',
            name='promedio_progreso',
            field=models.FloatField(default=0, verbose_name='Promedio de progreso'),
        ),
    ]
