# Generated by Django 5.1 on 2024-10-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_progresovivienda_promedio_progreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_agua',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_ahorro',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_arboles',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_banio',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_capacitaciones',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_cerco',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_chequeo_embarazo',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_comida',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_divisiones',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_emergencia_embarazo',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_escuela',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_estufa',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_lavar_manos',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_letrina',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_limpieza',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_muebles',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_peso',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_piscicultura',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_piso',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_plagas',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_reciclaje',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_sumidero',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_tuberculos',
        ),
        migrations.RemoveField(
            model_name='progresovivienda',
            name='urgencia_vacunacion',
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='desparacitacion',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Vacunación y desparasitación'),
        ),
        migrations.AddField(
            model_name='progresovivienda',
            name='jaulas',
            field=models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Animales protegidos en jaulas'),
        ),
    ]
